export const districtWisePsMap = {
  തിരുവനന്തപുരം: ["തിരുവനന്തപുരം", "നെയ്യാറ്റിൻകര", "വെഞ്ഞാറമൂട്"],
  കൊല്ലം: ["തലവൂർ", "കൊട്ടാരക്കര"],
  പത്തനംതിട്ട: ["ഓമല്ലൂർ", "എഴുമറ്റൂർ"],
  ആലപ്പുഴ: [
    "ചേർത്തല",
    "തുറവൂർ",
    "കൂറ്റുവേലി",
    "ഹരിപ്പാട്",
    "കായംകുളം",
    "മണ്ണഞ്ചേരി",
  ],
  കോട്ടയം: ["കോട്ടയം", "വൈക്കം"],
  ഇടുക്കി: ["തൊടുപുഴ"],
  എറണാകുളം: [
    "എറണാകുളം",
    "പെരുമ്പാവൂർ",
    "ആലുവ",
    "ചോറ്റാനിക്കര",
    "തൃപ്പൂണിത്തുറ",
    "പനങ്ങാട്",
    "ഇടപ്പള്ളി",
  ],
  തൃശ്ശൂർ: [
    "തൃശ്ശൂർ",
    "വടക്കാഞ്ചേരി",
    "മുകുന്ദപുരം",
    "കുന്ദംകുളം",
    "ഗുരുവായൂർ",
    "തൃപ്രയാർ",
    "ചേർപ്പ്",
  ],
  പാലക്കാട്: ["ഒറ്റപ്പാലം", "പാലക്കാട്", "പട്ടാമ്പി"],
  മലപ്പുറം: [
    "മഞ്ചേരി",
    "പൊന്നാനി",
    "വണ്ടൂർ",
    "മലപ്പുറം",
    "തിരൂർ",
    "പരപ്പനങ്ങാടി",
  ],
  കോഴിക്കോട്: [
    "കൊയിലാണ്ടി",
    "താമരശ്ശേരി",
    "വേങ്ങേരി",
    "ചേവായൂർ",
    "കക്കോടി",
    "കോട്ടൂർ",
    "തൃക്കുറ്റിശ്ശേരി",
    "വെസ്റ്റ് ഹിൽ",
    "പേരാമ്പ്ര",
    "നിട്ടൂർ",
    "രാമനാട്ടുകര",
    "പാലക്കോട്",
  ],
  വയനാട്: ["പനമരം", "മാനന്തവാടി"],
  കണ്ണൂർ: [
    "പയ്യന്നൂർ",
    "ആലപ്പടമ്പ",
    "അറത്തിൽ",
    "തലശ്ശേരി",
    "വടവന്തൂർ",
    "മട്ടന്നൂർ",
    "മുഴക്കുന്ന്",
    "തളിപ്പറമ്പ്",
  ],
  കാസർഗോഡ്: ["ഹോസ്‌ദുർഗ്", "കാസർഗോഡ്"],
  "Outside Kerala": [
    "ഹൈദരാബാദ്",
    "കോയമ്പത്തൂർ",
    "ചെന്നൈ",
    "ഈറോഡ്",
    "ഡൽഹി",
    "അഹമ്മദാബാദ്",
    "ബാംഗ്ലൂർ",
    "ബാന്ദ്ര",
    "മുംബൈ",
    "മസ്‌ക്കറ്റ്",
    "Others",
  ],
};

export const queryCategories = [
  "General",
  "Transporation",
  "Accommodation",
  "Offcial Program",
  "Cultural Program",
  "Souvenir",
  "Contests",
  "Website Content",
  "Venue",
  "Food",
  "Advertisement",
  "Publc Relations",
];

export const ecMemberList = [
  { Id: "EC-01", Name: "L.P. Viswanathan" },
  { Id: "EC-02", Name: "P.V.Sudheer Nambisan" },
  { Id: "EC-03", Name: "T.R. Harinarayanan" },
  { Id: "EC-04", Name: "P.R.Hari" },
  { Id: "EC-05", Name: "K.N.Krishnan Nambisan" },
  { Id: "EC-06", Name: "T.M.Ravidran Nambisan" },
  { Id: "EC-07", Name: "K.M.Sanoj" },
  { Id: "EC-08", Name: "Rajan P.S." },
  { Id: "EC-09", Name: "A.B.Balamurali" },
  { Id: "EC-10", Name: "K.M. Devakikutty" },
  { Id: "EC-11", Name: "B.Satheesh Kumar" },
  { Id: "EC-12", Name: "T.V.Venugopal" },
  { Id: "EC-13", Name: "Dr.Pradeep Jeothi" },
  { Id: "EC-14", Name: "Dr.P.Gopeenathan" },
  { Id: "EC-15", Name: "Satheesh.V.N" },
  { Id: "EC-16", Name: "Dr. D.Neelakandan" },
];

export const bsMemberList = [
  { Id: "BS-01", Name: "Nambisan.P.P." },
  { Id: "BS-02", Name: "Muraleekumar .A." },
  { Id: "BS-03", Name: "Muraleedharan R. Dr" },
  { Id: "BS-04", Name: "Mohanan Nambisan V.M." },
  { Id: "BS-05", Name: "Mohanachandran T.N." },
  { Id: "BS-06", Name: "Dr.Lekha Radhakrishnan" },
  { Id: "BS-07", Name: "Krishnan Nambisan K.P." },
  { Id: "BS-08", Name: "Krishnamoorthy P.N." },
  { Id: "BS-09", Name: "Krishna Prasad V.M." },
  { Id: "BS-10", Name: "Krishna Prasad P.N" },
  { Id: "BS-11", Name: "Kesavan Nambisan" },
  { Id: "BS-12", Name: "Jayasree Parameswaran" },
  { Id: "BS-13", Name: "Jayan M.P." },
  { Id: "BS-14", Name: "Jayadevan Unni V" },
  { Id: "BS-15", Name: "Jalaja M.P." },
  { Id: "BS-16", Name: "Jagadeesan T.M." },
  { Id: "BS-17", Name: "Harikumar T.R." },
  { Id: "BS-18", Name: "Dinesh Kumar G" },
  { Id: "BS-19", Name: "Deepa Girish" },
  { Id: "BS-20", Name: "Damodaran Nambisan.E" },
  { Id: "BS-21", Name: "Binu Balan" },
  { Id: "BS-22", Name: "Balan Nambisan K" },
  { Id: "BS-23", Name: "Asha P.S." },
  { Id: "BS-24", Name: "Anoop Unni" },
  { Id: "BS-25", Name: "Anil V.N." },
  { Id: "BS-26", Name: "Anand Kesavan P.K." },
  { Id: "BS-27", Name: "Abhijith M.G." },
  { Id: "BS-28", Name: "Vinod Kumar Nambisan.V" },
  { Id: "BS-29", Name: "Vijayan V.M." },
  { Id: "BS-30", Name: "Vijayan Nambisan T.P." },
  { Id: "BS-31", Name: "Vijaya SankarT.M." },
  { Id: "BS-32", Name: "Vijaya Kumar.E." },
  { Id: "BS-33", Name: "Vasu Pradeep T.M." },
  { Id: "BS-34", Name: "Unnikrishnan.V" },
  { Id: "BS-35", Name: "Suresh Kumar S" },
  { Id: "BS-36", Name: "Sujatha Krishnakumar" },
  { Id: "BS-37", Name: "Sreeja K.V." },
  { Id: "BS-38", Name: "Sreedevi C.P." },
  { Id: "BS-39", Name: "Sivasankaran E.D" },
  { Id: "BS-40", Name: "Sathi Kesavan" },
  { Id: "BS-41", Name: "Sankar T.V." },
  { Id: "BS-42", Name: "Ravindran.V.Dr." },
  { Id: "BS-43", Name: "Raveendra Kumar D" },
  { Id: "BS-44", Name: "Rajendra Sarma" },
  { Id: "BS-45", Name: "Rajan.E." },
  { Id: "BS-46", Name: "Rajan Nambisan P.V." },
  { Id: "BS-47", Name: "Rajan K.T." },
  { Id: "BS-48", Name: "Priyanka Mohan" },
  { Id: "BS-49", Name: "Prashanth V" },
  { Id: "BS-50", Name: "Prasad Arayala" },
];

export const kendraPrathinidhiList = {
  തിരുവനന്തപുരം: {
    തിരുവനന്തപുരം: [
      { Id: "TRV-TRV-01", Name: "Dr Pradeep Gopal Das Jeothi" },
      { Id: "TRV-TRV-02", Name: "K Sankaran Unni" },
      { Id: "TRV-TRV-03", Name: "B Byju" },
      { Id: "TRV-TRV-04", Name: "D Rajendra kumar" },
      { Id: "TRV-TRV-05", Name: "Sudheer Babu N" },
      { Id: "TRV-TRV-06", Name: "Suresh Kurukkal" },
      { Id: "TRV-TRV-07", Name: "Indira Pradeep" },
      { Id: "TRV-TRV-08", Name: "K M Sreedevikutty" },
      { Id: "TRV-TRV-09", Name: "J Radhamani" },
      { Id: "TRV-TRV-10", Name: "O Vijayalakshmi" },
      { Id: "TRV-TRV-11", Name: "V R Krishnan Nambeesan" },
      { Id: "TRV-TRV-12", Name: "M A G Nambeesan" },
      { Id: "TRV-TRV-13", Name: "R Hariharadas" },
      { Id: "TRV-TRV-14", Name: "KG Ajithkumar" },
      { Id: "TRV-TRV-15", Name: "J Padma" },
      { Id: "TRV-TRV-16", Name: "Prabhavathy Amma L" },
      { Id: "TRV-TRV-17", Name: "T.R.Harikumar" },
      { Id: "TRV-TRV-18", Name: "Akshay G Unni" },
      { Id: "TRV-TRV-19", Name: "Shashikala Krishnan" },
      { Id: "TRV-TRV-20", Name: "Krishnasarma S" },
    ],
    നെയ്യാറ്റിൻകര: [
      { Id: "TRV-NTK-01", Name: "LP Viswanadhan" },
      { Id: "TRV-NTK-02", Name: "KM Devaki kutty" },
      { Id: "TRV-NTK-03", Name: "Sreedevi suresh" },
      { Id: "TRV-NTK-04", Name: "JN Ajith Kumar" },
      { Id: "TRV-NTK-05", Name: "Chandra Kumar G" },
      { Id: "TRV-NTK-06", Name: "Suresh Kumar S" },
      { Id: "TRV-NTK-07", Name: "V Pradeep" },
      { Id: "TRV-NTK-08", Name: "Krishna kurukkal" },
      { Id: "TRV-NTK-09", Name: "Janardhanadev S" },
      { Id: "TRV-NTK-10", Name: "S Ajaya Kumar" },
      { Id: "TRV-NTK-11", Name: "Vibhu Kumar BR" },
    ],
    വെഞ്ഞാറമൂട്: [
      { Id: "TRV-VJM-01", Name: "Dinesh kumar G" },
      { Id: "TRV-VJM-02", Name: "Ravi Kumar D" },
      { Id: "TRV-VJM-03", Name: "Raju VS" },
      { Id: "TRV-VJM-04", Name: "Girija Kumari S" },
      { Id: "TRV-VJM-05", Name: "Vasantha S" },
      { Id: "TRV-VJM-06", Name: "Vidhu VL" },
    ],
  },
  കൊല്ലം: {
    തലവൂർ: [
      { Id: "KLM-TLV-01", Name: "Parameswaran Unni" },
      { Id: "KLM-TLV-02", Name: "Madhusoodhanan Unni G" },
      { Id: "KLM-TLV-03", Name: "Balakrishan Unni K" },
      { Id: "KLM-TLV-04", Name: "Sajeevan Unni" },
      { Id: "KLM-TLV-05", Name: "Ajayan Unni A" },
      { Id: "KLM-TLV-06", Name: "Abhijith MG" },
      { Id: "KLM-TLV-07", Name: "Santhosh Sharma. N" },
      { Id: "KLM-TLV-08", Name: "Indrasenan Unni" },
      { Id: "KLM-TLV-09", Name: "C Vasudevan Nambiar" },
    ],
  },
  കോട്ടയം: {
    കോട്ടയം: [
      { Id: "KTM-KTM-01", Name: "KN Narayanan Unni" },
      { Id: "KTM-KTM-02", Name: "Rajeev N Plapally" },
      { Id: "KTM-KTM-03", Name: "Prasanth V" },
      { Id: "KTM-KTM-04", Name: "Geetha Devi N" },
      { Id: "KTM-KTM-05", Name: "Damodaran Unni C S" },
    ],
    വൈക്കം: [
      { Id: "KTM-VKM-01", Name: "Narayanan K" },
      { Id: "KTM-VKM-02", Name: "Prabha Krishnan Nambiar" },
      { Id: "KTM-VKM-03", Name: "Krishna kumar K S" },
      { Id: "KTM-VKM-04", Name: "Saradadevi T K" },
      { Id: "KTM-VKM-05", Name: "Narayanan Unni V" },
      { Id: "KTM-VKM-06", Name: "Harisankar N Unni" },
    ],
  },
  പത്തനംതിട്ട: {
    എഴുമറ്റൂർ: [
      { Id: "PTA-ETR-01", Name: "Remya Sharma" },
      { Id: "PTA-ETR-02", Name: "Sasidhara Sharma" },
      { Id: "PTA-ETR-03", Name: "Rajendra Sarma" },
    ],
  },
  ഇടുക്കി: {
    തൊടുപുഴ: [{ Id: "IDK-TDP-01", Name: "Raghu N plapallay" }],
  },
  ആലപ്പുഴ: {
    ചേർത്തല: [
      { Id: "ALP-CTL-01", Name: "Narayanan Unni KP" },
      { Id: "ALP-CTL-02", Name: "Jalaja Mohan" },
      { Id: "ALP-CTL-03", Name: "Rajan N Unni" },
      { Id: "ALP-CTL-04", Name: "Mohanan Unni" },
      { Id: "ALP-CTL-05", Name: "Dr Sreedevi KS" },
      { Id: "ALP-CTL-06", Name: "Anandavalli" },
    ],
    ഹരിപ്പാട്: [
      { Id: "ALP-HPD-01", Name: "Vasudevan Unni" },
      { Id: "ALP-HPD-02", Name: "V Narayanan Unni" },
      { Id: "ALP-HPD-03", Name: "Subrahmaniya Swami" },
      { Id: "ALP-HPD-04", Name: "Venugopal PS" },
    ],
    കായംകുളം: [
      { Id: "ALP-KYM-01", Name: "Vijayan Unni" },
      { Id: "ALP-KYM-02", Name: "Arun Kumar" },
      { Id: "ALP-KYM-03", Name: "Sreekumar S" },
      { Id: "ALP-KYM-04", Name: "Sreejith S" },
    ],
    കൂറ്റുവേലി: [
      { Id: "ALP-KTV-01", Name: "KS Pradeep" },
      { Id: "ALP-KTV-02", Name: "Smitha Pradeep" },
      { Id: "ALP-KTV-03", Name: "Aji R" },
      { Id: "ALP-KTV-04", Name: "Parameswaran Unni V" },
      { Id: "ALP-KTV-05", Name: "AB Balamurali" },
      { Id: "ALP-KTV-06", Name: "Raveendra Kumar D" },
      { Id: "ALP-KTV-07", Name: "Omana Balamurali" },
      { Id: "ALP-KTV-08", Name: "Praveena Pramod" },
      { Id: "ALP-KTV-09", Name: "Ananthu S Varma" },
      { Id: "ALP-KTV-10", Name: "TP Balachandran" },
      { Id: "ALP-KTV-11", Name: "Geetha S Unni" },
      { Id: "ALP-KTV-12", Name: "Sunil Kumar" },
      { Id: "ALP-KTV-13", Name: "Gopinathan Unni N" },
      { Id: "ALP-KTV-14", Name: "Sindhu Sunil Kumar" },
      { Id: "ALP-KTV-15", Name: "Abhilash" },
      { Id: "ALP-KTV-16", Name: "Subrahmanya Sharma" },
    ],
    മണ്ണഞ്ചേരി: [
      { Id: "ALP-MNC-01", Name: "Satheesh Kumar" },
      { Id: "ALP-MNC-02", Name: "Rema Satheesh" },
      { Id: "ALP-MNC-03", Name: "Unnikrishnan" },
      { Id: "ALP-MNC-04", Name: "Jayadevan Unni V" },
      { Id: "ALP-MNC-05", Name: "Vishnu CN" },
    ],
    തുറവൂർ: [
      { Id: "ALP-TRV-01", Name: "Radhakrishnan Unni" },
      { Id: "ALP-TRV-02", Name: "Rajendran Unni" },
      { Id: "ALP-TRV-03", Name: "Ramachandran K N" },
      { Id: "ALP-TRV-04", Name: "Chandrasekharan Unni" },
      { Id: "ALP-TRV-05", Name: "Lalitha E" },
      { Id: "ALP-TRV-06", Name: "Dr.Lekha Radhakrishnan" },
    ],
  },
  എറണാകുളം: {
    ആലുവ: [
      { Id: "EKM-ALV-01", Name: "T K Krishnan" },
      { Id: "EKM-ALV-02", Name: "Jayasankar N" },
      { Id: "EKM-ALV-03", Name: "PR Bahrathy" },
      { Id: "EKM-ALV-04", Name: "CS Kesavan Nambeesan" },
      { Id: "EKM-ALV-05", Name: "SK Gireesan" },
      { Id: "EKM-ALV-06", Name: "Sivasankaran ED" },
      { Id: "EKM-ALV-07", Name: "RS Nambiar" },
      { Id: "EKM-ALV-08", Name: "Indu Narayanan" },
      { Id: "EKM-ALV-09", Name: "Kavitha Hari" },
    ],
    ചോറ്റാനിക്കര: [
      { Id: "EKM-CTK-01", Name: "Subramonian Unni PN" },
      { Id: "EKM-CTK-02", Name: "Venugopalan K" },
      { Id: "EKM-CTK-03", Name: "Nandakumar Sharma" },
      { Id: "EKM-CTK-04", Name: "Balasubramonyan KA" },
      { Id: "EKM-CTK-05", Name: "Keshavan Nambiar VP" },
      { Id: "EKM-CTK-06", Name: "Anoop Unni" },
      { Id: "EKM-CTK-07", Name: "Narayanan Unni" },
      { Id: "EKM-CTK-08", Name: "Usha Keshavan" },
      { Id: "EKM-CTK-09", Name: "Harish PN" },
      { Id: "EKM-CTK-10", Name: "Narayanan Nambiar TP" },
      { Id: "EKM-CTK-11", Name: "Pradeep N A" },
    ],
    ഇടപ്പള്ളി: [
      { Id: "EKM-EDP-01", Name: "Vikas RD" },
      { Id: "EKM-EDP-02", Name: "Raman Nambisan CN" },
      { Id: "EKM-EDP-03", Name: "Sathish CR" },
      { Id: "EKM-EDP-04", Name: "Mohana Chandran TN" },
      { Id: "EKM-EDP-05", Name: "Jayadevan TN" },
      { Id: "EKM-EDP-06", Name: "K Unnikrishnan" },
      { Id: "EKM-EDP-07", Name: "C P Krishnan" },
      { Id: "EKM-EDP-08", Name: "TV Ganesh Kumar" },
      { Id: "EKM-EDP-09", Name: "Geetha satheesh" },
      { Id: "EKM-EDP-10", Name: "Sreedevi Roojith" },
      { Id: "EKM-EDP-11", Name: "Dr.Remya Vikas" },
      { Id: "EKM-EDP-12", Name: "Neelakandan Unni" },
    ],
    എറണാകുളം: [
      { Id: "EKM-EKM-01", Name: "Unnikrishnan V" },
      { Id: "EKM-EKM-02", Name: "Sankar TV" },
      { Id: "EKM-EKM-03", Name: "Savithri Sankar" },
      { Id: "EKM-EKM-04", Name: "Prameela Narayanan" },
      { Id: "EKM-EKM-05", Name: "Girish NG" },
      { Id: "EKM-EKM-06", Name: "Vimalkumar sarma kn" },
      { Id: "EKM-EKM-07", Name: "Jithin unni" },
      { Id: "EKM-EKM-08", Name: "Murali K S" },
      { Id: "EKM-EKM-09", Name: "Gopakumar V" },
      { Id: "EKM-EKM-10", Name: "Ramachandran MK" },
      { Id: "EKM-EKM-11", Name: "Rajkumar v" },
      { Id: "EKM-EKM-12", Name: "Sreekumar KG" },
      { Id: "EKM-EKM-13", Name: "Ramachandran unni ks" },
    ],
    പനങ്ങാട്: [
      { Id: "EKM-PGD-01", Name: "Deepesh Darsan" },
      { Id: "EKM-PGD-02", Name: "Surendra unni CK" },
      { Id: "EKM-PGD-03", Name: "Sreekumar k" },
      { Id: "EKM-PGD-04", Name: "Rajesh V" },
    ],
    പെരുമ്പാവൂർ: [
      { Id: "EKM-PBV-01", Name: "Rajalakshmi ramachandran" },
      { Id: "EKM-PBV-02", Name: "Vasudevan TR" },
      { Id: "EKM-PBV-03", Name: "Suma K V" },
      { Id: "EKM-PBV-04", Name: "Umadevi P R" },
      { Id: "EKM-PBV-05", Name: "K V vasudevan" },
      { Id: "EKM-PBV-06", Name: "Ganesh K R" },
      { Id: "EKM-PBV-07", Name: "Prasanna krishkumar" },
      { Id: "EKM-PBV-08", Name: "Dhanesh vijayan" },
      { Id: "EKM-PBV-09", Name: "Girija AP" },
      { Id: "EKM-PBV-10", Name: "Praveen K G" },
      { Id: "EKM-PBV-11", Name: "KN Krishnan Nambisan" },
      { Id: "EKM-PBV-12", Name: "Narayanan V" },
      { Id: "EKM-PBV-13", Name: "N Sankaran Nambiar" },
      { Id: "EKM-PBV-14", Name: "Ramachandran P" },
      { Id: "EKM-PBV-15", Name: "Anitha Vasudevan" },
    ],
    തൃപ്പൂണിത്തുറ: [
      { Id: "EKM-TPR-01", Name: "Lakshmi Narayanan" },
      { Id: "EKM-TPR-02", Name: "Jayan MP" },
      { Id: "EKM-TPR-03", Name: "KP Umadevi" },
      { Id: "EKM-TPR-04", Name: "Bhavadasan P" },
      { Id: "EKM-TPR-05", Name: "Anil Kumar K N" },
      { Id: "EKM-TPR-06", Name: "Balakrishnan P" },
    ],
  },
  തൃശ്ശൂർ: {
    ചേർപ്പ്: [
      { Id: "TSR-CHE-01", Name: "AV Sankaran Nambisan" },
      { Id: "TSR-CHE-02", Name: "P Parameswaran" },
      { Id: "TSR-CHE-03", Name: "Renjith Vasudevan" },
      { Id: "TSR-CHE-04", Name: "Resmi Renjith" },
      { Id: "TSR-CHE-05", Name: "Asha PS" },
      { Id: "TSR-CHE-06", Name: "Dr R Muraleedharan" },
      { Id: "TSR-CHE-07", Name: "T P Murali" },
    ],
    ഗുരുവായൂർ: [
      { Id: "TSR-GVR-01", Name: "Rema venugopal" },
      { Id: "TSR-GVR-02", Name: "Aneesh CN" },
      { Id: "TSR-GVR-03", Name: "Sreedharan" },
      { Id: "TSR-GVR-04", Name: "Raman nambissan" },
      { Id: "TSR-GVR-05", Name: "Krishnadas ," },
      { Id: "TSR-GVR-06", Name: "AP Rajam" },
      { Id: "TSR-GVR-07", Name: "Sreeja Satheeshan PN" },
      { Id: "TSR-GVR-08", Name: "Vineeth kesavan nambissan" },
      { Id: "TSR-GVR-09", Name: "Venugopal TV" },
      { Id: "TSR-GVR-10", Name: "Narayanan PV" },
    ],
    കുന്ദംകുളം: [
      { Id: "TSR-KNK-01", Name: "Balan Nambisan K" },
      { Id: "TSR-KNK-02", Name: "Ramachandran TP" },
      { Id: "TSR-KNK-03", Name: "Santhosh Nambisan" },
      { Id: "TSR-KNK-04", Name: "Swasthi Chandran" },
      { Id: "TSR-KNK-05", Name: "Pushpa Balan" },
      { Id: "TSR-KNK-06", Name: "Aswathy santhosh" },
      { Id: "TSR-KNK-07", Name: "Ramachandran Sarma" },
      { Id: "TSR-KNK-08", Name: "Rajeesh N R" },
      { Id: "TSR-KNK-09", Name: "Purushottaman nambissan" },
    ],
    മുകുന്ദപുരം: [
      { Id: "TSR-MDP-01", Name: "TP Vijayan Nambisan" },
      { Id: "TSR-MDP-02", Name: "TP Mohanan Nambisan" },
      { Id: "TSR-MDP-03", Name: "Sathi Vijayan" },
      { Id: "TSR-MDP-04", Name: "D Indira" },
      { Id: "TSR-MDP-05", Name: "Dr Harinarayanan" },
      { Id: "TSR-MDP-06", Name: "Jyothi KV" },
      { Id: "TSR-MDP-07", Name: "M vasudevan nambissan" },
      { Id: "TSR-MDP-08", Name: "VP Krishnan kutty nambissan" },
      { Id: "TSR-MDP-09", Name: "Radha EN" },
      { Id: "TSR-MDP-10", Name: "Vanaja sudhakaran" },
      { Id: "TSR-MDP-11", Name: "Yamuna PR" },
      { Id: "TSR-MDP-12", Name: "P Viswanatha Kurukkal" },
      { Id: "TSR-MDP-13", Name: "MN Sreekumar" },
      { Id: "TSR-MDP-14", Name: "TU Parameswaran" },
      { Id: "TSR-MDP-15", Name: "Narayanan ON" },
    ],
    തൃശ്ശൂർ: [
      { Id: "TSR-TSR-01", Name: "Neelakantan V P" },
      { Id: "TSR-TSR-02", Name: "Sankaran Nambissan P S" },
      { Id: "TSR-TSR-03", Name: "Narayanan Nambeesan K P" },
      { Id: "TSR-TSR-04", Name: "Chandrika krishnan" },
      { Id: "TSR-TSR-05", Name: "Kalidasan K N" },
      { Id: "TSR-TSR-06", Name: "Krishnan T N" },
      { Id: "TSR-TSR-07", Name: "Mohanan Nambissan" },
      { Id: "TSR-TSR-08", Name: "Sankaran A N" },
      { Id: "TSR-TSR-09", Name: "Adv Sreelatha TN" },
      { Id: "TSR-TSR-10", Name: "PRATHEEK P. R." },
      { Id: "TSR-TSR-11", Name: "Prof Krishna kumar T" },
      { Id: "TSR-TSR-12", Name: "Ramabhadran M" },
      { Id: "TSR-TSR-13", Name: "Ramachandran K N" },
      { Id: "TSR-TSR-14", Name: "Krishna Prasad P N" },
      { Id: "TSR-TSR-15", Name: "Sudheesh p" },
      { Id: "TSR-TSR-16", Name: "Anand kesavan" },
      { Id: "TSR-TSR-17", Name: "Girija Neelakandan" },
      { Id: "TSR-TSR-18", Name: "Kesavan C S" },
      { Id: "TSR-TSR-19", Name: "Jayakumari V" },
      { Id: "TSR-TSR-20", Name: "Raj Narayanan KV" },
      { Id: "TSR-TSR-21", Name: "Ramachandran P R" },
      { Id: "TSR-TSR-22", Name: "Nandakumar A P" },
      { Id: "TSR-TSR-23", Name: "Aryadevi K" },
      { Id: "TSR-TSR-24", Name: "Rakesh kp" },
      { Id: "TSR-TSR-25", Name: "Sreenath Nambiar" },
      { Id: "TSR-TSR-26", Name: "Radha Neelakantan" },
      { Id: "TSR-TSR-27", Name: "Narayanan Nambeesan A P" },
      { Id: "TSR-TSR-28", Name: "Anuroop p" },
      { Id: "TSR-TSR-29", Name: "Sreedevi C P" },
      { Id: "TSR-TSR-30", Name: "Narayanan V K" },
      { Id: "TSR-TSR-31", Name: "Neelakantan T N" },
      { Id: "TSR-TSR-32", Name: "P Krishnan Nambisan" },
      { Id: "TSR-TSR-33", Name: "Narayanan Nambisan" },
      { Id: "TSR-TSR-34", Name: "Preetha Raju" },
      { Id: "TSR-TSR-35", Name: "Rema kesavan" },
      { Id: "TSR-TSR-36", Name: "Sreedevi Ramachandran" },
      { Id: "TSR-TSR-37", Name: "MP Ramachandran" },
      { Id: "TSR-TSR-38", Name: "Suresh nambissan M P" },
      { Id: "TSR-TSR-39", Name: "Renuka Rakesh" },
      { Id: "TSR-TSR-40", Name: "Subhada Anuroop" },
      { Id: "TSR-TSR-41", Name: "Navaneeth" },
    ],
    വടക്കാഞ്ചേരി: [
      { Id: "TSR-WDK-01", Name: "K C Radhakrishnan" },
      { Id: "TSR-WDK-02", Name: "Kavil Narayanan," },
      { Id: "TSR-WDK-03", Name: "Anil . V.N." },
      { Id: "TSR-WDK-04", Name: "N R Mohanan" },
      { Id: "TSR-WDK-05", Name: "Dr D Neelakandan" },
      { Id: "TSR-WDK-06", Name: "TN Nambisan" },
      { Id: "TSR-WDK-07", Name: "R Sreedevi" },
      { Id: "TSR-WDK-08", Name: "Prakash T" },
      { Id: "TSR-WDK-09", Name: "CP Neelakandan" },
      { Id: "TSR-WDK-10", Name: "Leela Nambissan" },
      { Id: "TSR-WDK-11", Name: "K S Narayanan Nambissan" },
      { Id: "TSR-WDK-12", Name: "Sangeetha Pradeep" },
      { Id: "TSR-WDK-13", Name: "Prasida Naveen" },
      { Id: "TSR-WDK-14", Name: "Hari PR" },
      { Id: "TSR-WDK-15", Name: "Rekha Nandakumar" },
      { Id: "TSR-WDK-16", Name: "Ramakrishnan A" },
      { Id: "TSR-WDK-17", Name: "Anoop N" },
      { Id: "TSR-WDK-18", Name: "Prakash D" },
      { Id: "TSR-WDK-19", Name: "Krishnan unni" },
      { Id: "TSR-WDK-20", Name: "Sreedevi P N" },
      { Id: "TSR-WDK-21", Name: "Hari Kumar KR" },
      { Id: "TSR-WDK-22", Name: "Girija Neelakandan" },
      { Id: "TSR-WDK-23", Name: "Muraliram T R" },
      { Id: "TSR-WDK-24", Name: "Devaki parameswaran" },
    ],
    തൃപ്രയാർ: [
      { Id: "TSR-TPR-01", Name: "P Krishnan Nambisan" },
      { Id: "TSR-TPR-02", Name: "Narayanan Nambisan" },
      { Id: "TSR-TPR-03", Name: "Preetha Raju" },
      { Id: "TSR-TPR-04", Name: "Rema Kesavan" },
      { Id: "TSR-TPR-05", Name: "Sreedevi Ramachandran" },
      { Id: "TSR-TPR-06", Name: "M P Ramachandran" },
      { Id: "TSR-TPR-07", Name: "Suresh nambissan M P" },
    ],
  },
  പാലക്കാട്: {
    ഒറ്റപ്പാലം: [
      { Id: "PKD-OTP-01", Name: "Raghunathan K" },
      { Id: "PKD-OTP-02", Name: "Kavitha Manoj" },
      { Id: "PKD-OTP-03", Name: "M D Unnikrishnan" },
      { Id: "PKD-OTP-04", Name: "Ramachandran V N" },
      { Id: "PKD-OTP-05", Name: "Satheesh Kumar M D" },
      { Id: "PKD-OTP-06", Name: "Rajan P S" },
      { Id: "PKD-OTP-07", Name: "Remakesavan" },
      { Id: "PKD-OTP-08", Name: "Vijayakumar P" },
      { Id: "PKD-OTP-09", Name: "Hemalatha Rajan" },
      { Id: "PKD-OTP-10", Name: "Santhosh P N" },
    ],
    പാലക്കാട്: [
      { Id: "PKD-PKD-01", Name: "K Balasubramonian" },
      { Id: "PKD-PKD-02", Name: "K P Chandrika Krishnan" },
      { Id: "PKD-PKD-03", Name: "P M Vasudevan Nambissan" },
      { Id: "PKD-PKD-04", Name: "K P Usha Devi" },
      { Id: "PKD-PKD-05", Name: "C Neelakandan Nambissan" },
      { Id: "PKD-PKD-06", Name: "T P Rajan" },
      { Id: "PKD-PKD-07", Name: "V Sankaran Nambisan" },
      { Id: "PKD-PKD-08", Name: "P D Keshavan Nambisan" },
      { Id: "PKD-PKD-09", Name: "Sathi Keshavan" },
      { Id: "PKD-PKD-10", Name: "Sathyanarayanan S N" },
      { Id: "PKD-PKD-11", Name: "Valsala Sathyanarayanan" },
    ],
    പട്ടാമ്പി: [
      { Id: "PKD-PTB-01", Name: "K P Krishnan Nambisan" },
      { Id: "PKD-PTB-02", Name: "P N Nambisan" },
      { Id: "PKD-PTB-03", Name: "Dr E N Unnikrishnan" },
      { Id: "PKD-PTB-04", Name: "T R Damodaran Nambisan" },
      { Id: "PKD-PTB-05", Name: "T P Leela" },
      { Id: "PKD-PTB-06", Name: "V Pushkala" },
      { Id: "PKD-PTB-07", Name: "K Kesavan Nambisan" },
      { Id: "PKD-PTB-08", Name: "Vasantha Vasudevan" },
      { Id: "PKD-PTB-09", Name: "K P Devarajan" },
    ],
  },
  മലപ്പുറം: {
    മലപ്പുറം: [
      { Id: "MLP-MLP-01", Name: "M P Suresh" },
      { Id: "MLP-MLP-02", Name: "K M Parameswaran Nambisan" },
      { Id: "MLP-MLP-03", Name: "M P Narayanan Nambisan" },
      { Id: "MLP-MLP-04", Name: "Jayasree Parameswaran" },
      { Id: "MLP-MLP-05", Name: "Santha Damodaran" },
    ],
    മഞ്ചേരി: [
      { Id: "MLP-MJR-01", Name: "K Sadanandan" },
      { Id: "MLP-MJR-02", Name: "P P Nambisan" },
      { Id: "MLP-MJR-03", Name: "P Unnikrishnan Nambisan" },
      { Id: "MLP-MJR-04", Name: "G K Madhu" },
      { Id: "MLP-MJR-05", Name: "P K Kesavan Nambisan" },
      { Id: "MLP-MJR-06", Name: "O Parameswaran Nambisan" },
      { Id: "MLP-MJR-07", Name: "Chandrika A P" },
      { Id: "MLP-MJR-08", Name: "Savithri Unnikrishnan" },
      { Id: "MLP-MJR-09", Name: "D Damodaran Nambisan" },
      { Id: "MLP-MJR-10", Name: "M P Chithra" },
      { Id: "MLP-MJR-11", Name: "Savitri Damodaran" },
      { Id: "MLP-MJR-12", Name: "Prema Oranadath" },
    ],
    പരപ്പനങ്ങാടി: [
      { Id: "MLP-PGD-01", Name: "Ramesan A P" },
      { Id: "MLP-PGD-02", Name: "Unnikrishnan A" },
      { Id: "MLP-PGD-03", Name: "Durga Das A P" },
      { Id: "MLP-PGD-04", Name: "Muraleekumar A" },
      { Id: "MLP-PGD-05", Name: "Praveen A" },
      { Id: "MLP-PGD-06", Name: "Krishnakumari" },
      { Id: "MLP-PGD-07", Name: "Vinodini" },
      { Id: "MLP-PGD-08", Name: "Sreenisha P V" },
    ],
    പൊന്നാനി: [
      { Id: "MLP-PNN-01", Name: "Dr. S Narayanan" },
      { Id: "MLP-PNN-02", Name: "P N Krishnamoorthy" },
      { Id: "MLP-PNN-03", Name: "P K Rajan" },
      { Id: "MLP-PNN-04", Name: "Renjith M" },
      { Id: "MLP-PNN-05", Name: "A P Sankara Narayanan" },
      { Id: "MLP-PNN-06", Name: "Geetha Rajan" },
    ],
    തിരൂർ: [
      { Id: "MLP-TRR-01", Name: "Damodaran Nambisan" },
      { Id: "MLP-TRR-02", Name: "Raghunathan Nambisan" },
      { Id: "MLP-TRR-03", Name: "Hari Narayanan T R" },
      { Id: "MLP-TRR-04", Name: "Mahesh T R" },
      { Id: "MLP-TRR-05", Name: "Prakash Vadakkath" },
      { Id: "MLP-TRR-06", Name: "Unnikrishnan Madathil" },
      { Id: "MLP-TRR-07", Name: "Sathi Devi K K" },
      { Id: "MLP-TRR-08", Name: "Sobha Damodaran" },
      { Id: "MLP-TRR-09", Name: "Sindhu Dhinesh" },
      { Id: "MLP-TRR-10", Name: "K Subramanian" },
      { Id: "MLP-TRR-11", Name: "K Unnikrishnan" },
      { Id: "MLP-TRR-12", Name: "Krishna Das T R" },
      { Id: "MLP-TRR-13", Name: "Gireesh" },
    ],
    വണ്ടൂർ: [
      { Id: "MLP-WDR-01", Name: "P Sreeprakash Nambisan" },
      { Id: "MLP-WDR-02", Name: "P Mohandas Nambisan" },
      { Id: "MLP-WDR-03", Name: "Umadevi" },
      { Id: "MLP-WDR-04", Name: "P Ramachandran Nambisan" },
      { Id: "MLP-WDR-05", Name: "Indira Ramachandran" },
      { Id: "MLP-WDR-06", Name: "K Ramachandran Nambisan" },
      { Id: "MLP-WDR-07", Name: "Sreedevi Mohandas" },
      { Id: "MLP-WDR-08", Name: "Anoop P" },
      { Id: "MLP-WDR-09", Name: "Geetha Ramachandran" },
      { Id: "MLP-WDR-10", Name: "Premalatha Unnikrishnan" },
      { Id: "MLP-WDR-11", Name: "E Damodaran Nambisan" },
      { Id: "MLP-WDR-12", Name: "T P Sashikumar" },
    ],
  },
  കോഴിക്കോട്: {
    ചേവായൂർ: [
      { Id: "CLT-CVR-01", Name: "Sudhakaran Nambisan N" },
      { Id: "CLT-CVR-02", Name: "Suresh Nambisan P" },
      { Id: "CLT-CVR-03", Name: "Sudheer Nambisan P V" },
      { Id: "CLT-CVR-04", Name: "Sunil Nambisan" },
      { Id: "CLT-CVR-05", Name: "Sujatha Krishnakumar" },
      { Id: "CLT-CVR-06", Name: "Suresh V Nambisan" },
      { Id: "CLT-CVR-07", Name: "Jayaraj Nambisan" },
      { Id: "CLT-CVR-08", Name: "M Rajan Nambisan" },
      { Id: "CLT-CVR-09", Name: "P V Krishnakumar Nambisan" },
      { Id: "CLT-CVR-10", Name: "Sobha Sudhakaran Nambisan" },
    ],
    കക്കോടി: [
      { Id: "CLT-KKD-01", Name: "Damodharan Nambisan P M" },
      { Id: "CLT-KKD-02", Name: "P P Mohanan Nambisan" },
      { Id: "CLT-KKD-03", Name: "P Unnikrishnan Nambisan" },
      { Id: "CLT-KKD-04", Name: "Prakashan Nambisan" },
      { Id: "CLT-KKD-05", Name: "Priyanka Mohan" },
      { Id: "CLT-KKD-06", Name: "Sindhu Dhanyesh" },
      { Id: "CLT-KKD-07", Name: "Jayarajan Nambisan V K" },
    ],
    കോട്ടൂർ: [
      { Id: "CLT-KTR-01", Name: "V N Dinesh Kumar" },
      { Id: "CLT-KTR-02", Name: "E Vijaya Kumar" },
      { Id: "CLT-KTR-03", Name: "Pramod K" },
      { Id: "CLT-KTR-04", Name: "Narayanan Nambisan P" },
    ],
    കൊയിലാണ്ടി: [
      { Id: "CLT-KLD-01", Name: "Sudheer Babu" },
      { Id: "CLT-KLD-02", Name: "Valsarajan T K" },
      { Id: "CLT-KLD-03", Name: "Sankaran Nambisan" },
      { Id: "CLT-KLD-04", Name: "Pramod P M" },
      { Id: "CLT-KLD-05", Name: "Unnikrishnan Nambisan P M" },
      { Id: "CLT-KLD-06", Name: "Praseeda Pramod" },
      { Id: "CLT-KLD-07", Name: "Sindhu Valsarajan" },
      { Id: "CLT-KLD-08", Name: "Suprabha K M" },
      { Id: "CLT-KLD-09", Name: "Muthu Saravanan M" },
    ],
    നിട്ടൂർ: [
      { Id: "CLT-NTR-01", Name: "Sundareshan P" },
      { Id: "CLT-NTR-02", Name: "Kesavan Nambissan" },
      { Id: "CLT-NTR-03", Name: "Sankaran Nambisan" },
      { Id: "CLT-NTR-04", Name: "Bijumon" },
      { Id: "CLT-NTR-05", Name: "Satheedevi" },
    ],
    പാലക്കോട്: [
      { Id: "CLT-PKD-01", Name: "Ajithakumari K" },
      { Id: "CLT-PKD-02", Name: "Dr Ravindran V" },
      { Id: "CLT-PKD-03", Name: "Soman N" },
      { Id: "CLT-PKD-04", Name: "Narayanan Nambisan N" },
      { Id: "CLT-PKD-05", Name: "Harikrishnan C M" },
      { Id: "CLT-PKD-06", Name: "Dr Latha D" },
      { Id: "CLT-PKD-07", Name: "Sayooj A" },
      { Id: "CLT-PKD-08", Name: "Rajan E" },
      { Id: "CLT-PKD-09", Name: "Sreeja P M" },
      { Id: "CLT-PKD-10", Name: "Jalaja C" },
      { Id: "CLT-PKD-11", Name: "Tharakeswari C" },
    ],
    പേരാമ്പ്ര: [
      { Id: "CLT-PRM-01", Name: "Balakrishnan Nambeesan M M" },
      { Id: "CLT-PRM-02", Name: "Ramachandran Pantheeradi" },
      { Id: "CLT-PRM-03", Name: "Harsha Kumar P" },
      { Id: "CLT-PRM-04", Name: "Suma Ambalakkandi" },
      { Id: "CLT-PRM-05", Name: "Girija P" },
      { Id: "CLT-PRM-06", Name: "Udayabhanu M P" },
    ],
    രാമനാട്ടുകര: [
      { Id: "CLT-RTK-01", Name: "Vijayan Nambisan" },
      { Id: "CLT-RTK-02", Name: "Anupama P" },
      { Id: "CLT-RTK-03", Name: "Krishna Kumari" },
      { Id: "CLT-RTK-04", Name: "Umadevi K M" },
      { Id: "CLT-RTK-05", Name: "M A Padmanabhan Nambisan" },
      { Id: "CLT-RTK-06", Name: "V Vinod Kumar Nambisan" },
      { Id: "CLT-RTK-07", Name: "Aravind Unnikrishnan" },
    ],
    വേങ്ങേരി: [
      { Id: "CLT-VGR-01", Name: "Muraleedharan P D" },
      { Id: "CLT-VGR-02", Name: "Sudheer Nambisan A G" },
      { Id: "CLT-VGR-03", Name: "Sudhevan Nambisan" },
      { Id: "CLT-VGR-04", Name: "Madhusoodanan P" },
      { Id: "CLT-VGR-05", Name: "Sreedharan Nambisan" },
      { Id: "CLT-VGR-06", Name: "Ramesan P" },
      { Id: "CLT-VGR-07", Name: "Ramadevi" },
      { Id: "CLT-VGR-08", Name: "Sunil Nambisan A G" },
      { Id: "CLT-VGR-09", Name: "Rekha Pradeep" },
    ],
    "വെസ്റ്റ് ഹിൽ": [
      { Id: "CLT-WHL-01", Name: "Ravindran M P" },
      { Id: "CLT-WHL-02", Name: "Saiprakash M T" },
      { Id: "CLT-WHL-03", Name: "Sreelesh E M" },
      { Id: "CLT-WHL-04", Name: "Narayanan K" },
      { Id: "CLT-WHL-05", Name: "Vasudevan A P" },
      { Id: "CLT-WHL-06", Name: "Jalaja M P" },
      { Id: "CLT-WHL-07", Name: "Pravitha K V" },
      { Id: "CLT-WHL-08", Name: "Vilasini Vijayan" },
      { Id: "CLT-WHL-09", Name: "Soudhamini Krishnan" },
      { Id: "CLT-WHL-10", Name: "Kesavan Nambissan P V" },
      { Id: "CLT-WHL-11", Name: "Sreejitha Poomadam" },
    ],
  },
  കണ്ണൂർ: {
    ആലപ്പടമ്പ: [
      { Id: "KNR-ALP-01", Name: "A M Kunhikrishnan Nambisan" },
      { Id: "KNR-ALP-02", Name: "T M K Santha" },
      { Id: "KNR-ALP-03", Name: "M Kesavan Unni" },
      { Id: "KNR-ALP-04", Name: "K V Sajeev Raj" },
      { Id: "KNR-ALP-05", Name: "K M Kunhikrishnan Nambisan" },
      { Id: "KNR-ALP-06", Name: "T M Suvarnini" },
      { Id: "KNR-ALP-07", Name: "T M Vasu Pradeep" },
      { Id: "KNR-ALP-08", Name: "Sankaran Kutty K M" },
      { Id: "KNR-ALP-09", Name: "P M Manjula" },
      { Id: "KNR-ALP-10", Name: "V M Eswaran" },
      { Id: "KNR-ALP-11", Name: "K M Kesavan Nambsan" },
      { Id: "KNR-ALP-12", Name: "Sankarankutty K M" },
      { Id: "KNR-ALP-13", Name: "T M Vishnu Nambisan" },
    ],
    അറത്തിൽ: [
      { Id: "KNR-ART-01", Name: "T M Ravindran" },
      { Id: "KNR-ART-02", Name: "T S Harikrishnan" },
      { Id: "KNR-ART-03", Name: "T S Sreejith" },
      { Id: "KNR-ART-04", Name: "V M Kesavan Nambisan" },
      { Id: "KNR-ART-05", Name: "T M Suresh Babu" },
      { Id: "KNR-ART-06", Name: "K M Somasundaran" },
      { Id: "KNR-ART-07", Name: "V M Venugopalan" },
      { Id: "KNR-ART-08", Name: "T M Savitha" },
      { Id: "KNR-ART-09", Name: "P M K Sajith Kumar" },
      { Id: "KNR-ART-10", Name: "T M Balagopalan" },
      { Id: "KNR-ART-11", Name: "C M Padmavathi" },
      { Id: "KNR-ART-12", Name: "Kesavan K M" },
      { Id: "KNR-ART-13", Name: "A Dakshayani" },
      { Id: "KNR-ART-14", Name: "Sindhu Venugopal" },
    ],
    മട്ടന്നൂർ: [
      { Id: "KNR-MTR-01", Name: "Dr. P Gopeenathan" },
      { Id: "KNR-MTR-02", Name: "Dr. Padma Gopeenathan" },
      { Id: "KNR-MTR-03", Name: "Sreeja K V" },
      { Id: "KNR-MTR-04", Name: "Unnikrishnan Nambisan T M" },
      { Id: "KNR-MTR-05", Name: "Sreeja Rajeev" },
      { Id: "KNR-MTR-06", Name: "Damodaran V V" },
      { Id: "KNR-MTR-07", Name: "Gopa Kumar P" },
      { Id: "KNR-MTR-08", Name: "Unnikrishnan K V" },
      { Id: "KNR-MTR-09", Name: "Hareendranathan V V" },
      { Id: "KNR-MTR-10", Name: "Dhanalakshmi" },
      { Id: "KNR-MTR-11", Name: "T M Vijaya Sankar" },
      { Id: "KNR-MTR-12", Name: "Sreekala Sathyan" },
      { Id: "KNR-MTR-13", Name: "Prakashan P K" },
      { Id: "KNR-MTR-14", Name: "Manjula Gopinath" },
      { Id: "KNR-MTR-15", Name: "Sudha Dinesh" },
      { Id: "KNR-MTR-16", Name: "Manjula Unnikrishnan" },
    ],
    മുഴക്കുന്ന്: [
      { Id: "KNR-MKN-01", Name: "Gireesh Kumar K M" },
      { Id: "KNR-MKN-02", Name: "Deepa Girish" },
      { Id: "KNR-MKN-03", Name: "Shyam Krishnan" },
      { Id: "KNR-MKN-04", Name: "Kalesan A" },
      { Id: "KNR-MKN-05", Name: "Balakrishnan M" },
    ],
    പയ്യന്നൂർ: [
      { Id: "KNR-PYR-01", Name: "T M Unnikrishnan Nambisan" },
      { Id: "KNR-PYR-02", Name: "M P Jayajith" },
      { Id: "KNR-PYR-03", Name: "Manoj Kumar K T" },
      { Id: "KNR-PYR-04", Name: "Manjula V M" },
      { Id: "KNR-PYR-05", Name: "Ramani Vishnu Nambisan" },
      { Id: "KNR-PYR-06", Name: "Mallika V M" },
      { Id: "KNR-PYR-07", Name: "V M Unnikrishnan Master" },
      { Id: "KNR-PYR-08", Name: "Roja Vijayan" },
      { Id: "KNR-PYR-09", Name: "Rathnakumari K" },
      { Id: "KNR-PYR-10", Name: "Vijayan V M" },
      { Id: "KNR-PYR-11", Name: "A M Balakrishnan" },
      { Id: "KNR-PYR-12", Name: "M V M Geethadevi" },
      { Id: "KNR-PYR-13", Name: "T M K Balakrishnan" },
    ],
    തലശ്ശേരി: [
      { Id: "KNR-TLS-01", Name: "K Udayakumar" },
      { Id: "KNR-TLS-02", Name: "K Radhakrishnan" },
      { Id: "KNR-TLS-03", Name: "K V Ramachandran" },
      { Id: "KNR-TLS-04", Name: "Rajalakshmy P" },
      { Id: "KNR-TLS-05", Name: "V K Viswanathan" },
      { Id: "KNR-TLS-06", Name: "V M Sumanadevi" },
      { Id: "KNR-TLS-07", Name: "Sreelatha V K" },
      { Id: "KNR-TLS-08", Name: "P V Rajan" },
    ],
    തളിപ്പറമ്പ്: [
      { Id: "KNR-TPB-01", Name: "V M Easwaran Nambisan" },
      { Id: "KNR-TPB-02", Name: "Vasudevan Nambisan P M" },
      { Id: "KNR-TPB-03", Name: "A M Kesavan Nambisan" },
      { Id: "KNR-TPB-04", Name: "K V Veeramani" },
      { Id: "KNR-TPB-05", Name: "P M Savithri" },
      { Id: "KNR-TPB-06", Name: "K M Kesavan Nambisan" },
      { Id: "KNR-TPB-07", Name: "V V Haridas" },
      { Id: "KNR-TPB-08", Name: "V M Devi Krishnan" },
      { Id: "KNR-TPB-09", Name: "Soorya Prasad" },
      { Id: "KNR-TPB-10", Name: "K T Rajan" },
      { Id: "KNR-TPB-11", Name: "K V Narayanan Nambisan" },
      { Id: "KNR-TPB-12", Name: "Prasad Arayala" },
      { Id: "KNR-TPB-13", Name: "Harshitha N K" },
      { Id: "KNR-TPB-14", Name: "A M Muralikrishnan" },
      { Id: "KNR-TPB-15", Name: "Bindu Veeramani" },
      { Id: "KNR-TPB-16", Name: "Parvathi K M" },
      { Id: "KNR-TPB-17", Name: "T M Narayanan Nambisan" },
    ],
    വടവന്തൂർ: [
      { Id: "KNR-VDR-01", Name: "Sadanandan K M" },
      { Id: "KNR-VDR-02", Name: "Muralikrishnan T E" },
      { Id: "KNR-VDR-03", Name: "Swathi P M" },
      { Id: "KNR-VDR-04", Name: "Sreeja Prasad K M" },
      { Id: "KNR-VDR-05", Name: "Prasad A M" },
      { Id: "KNR-VDR-06", Name: "Oormila C M" },
      { Id: "KNR-VDR-07", Name: "Jagadeesan T M" },
      { Id: "KNR-VDR-08", Name: "K M Sankaran Nambisan" },
      { Id: "KNR-VDR-09", Name: "K M Raghunathan Nambisan" },
      { Id: "KNR-VDR-10", Name: "Vasanthi T M" },
    ],
  },
  വയനാട്: {
    പനമരം: [
      { Id: "WYD-PNR-01", Name: "Sivaraman Nambeesan" },
      { Id: "WYD-PNR-02", Name: "Vasudevan T" },
      { Id: "WYD-PNR-03", Name: "Hari Narayanan" },
      { Id: "WYD-PNR-04", Name: "Kesavan Nambeesan" },
      { Id: "WYD-PNR-05", Name: "Vasumathi Nambeesan" },
      { Id: "WYD-PNR-06", Name: "Sathi Sivaraman" },
      { Id: "WYD-PNR-07", Name: "Seema Sujith" },
      { Id: "WYD-PNR-08", Name: "Vineetha Vivek" },
      { Id: "WYD-PNR-09", Name: "Vasupradeep" },
      { Id: "WYD-PNR-10", Name: "K P Narayanan" },
      { Id: "WYD-PNR-11", Name: "Santha Vasudevan" },
    ],
  },
  കാസർഗോഡ്: {
    ഹോസ്‌ദുർഗ്: [
      { Id: "KGD-HSR-01", Name: "Sanoj K M" },
      { Id: "KGD-HSR-02", Name: "N M Ratheesh Kumar" },
      { Id: "KGD-HSR-03", Name: "Sreedevi M" },
      { Id: "KGD-HSR-04", Name: "V M Vishnu Prasad" },
      { Id: "KGD-HSR-05", Name: "Suma Dineshan" },
      { Id: "KGD-HSR-06", Name: "V M Ramachandran Nambisan" },
      { Id: "KGD-HSR-07", Name: "K P Narayanan" },
      { Id: "KGD-HSR-08", Name: "Somanathan M" },
      { Id: "KGD-HSR-09", Name: "Narayanan N M" },
      { Id: "KGD-HSR-10", Name: "K M Radhakrishnan" },
    ],
    കാസർഗോഡ്: [
      { Id: "KGD-KGD-01", Name: "V M Krishna Prasad" },
      { Id: "KGD-KGD-02", Name: "U Balakrishna" },
      { Id: "KGD-KGD-03", Name: "K P Rajeevan" },
      { Id: "KGD-KGD-04", Name: "Prakashan P M" },
      { Id: "KGD-KGD-05", Name: "Balakrishnan P" },
      { Id: "KGD-KGD-06", Name: "Sreepriya Rajesh" },
      { Id: "KGD-KGD-07", Name: "A Venugopal" },
      { Id: "KGD-KGD-08", Name: "Rajesh E" },
    ],
  },
  "Outside Kerala": {
    ചെന്നൈ: [
      { Id: "OSK-CHN-01", Name: "Vijayan P M" },
      { Id: "OSK-CHN-02", Name: "Anand C" },
      { Id: "OSK-CHN-03", Name: "Binu Balan" },
      { Id: "OSK-CHN-04", Name: "Krishna Prasad K M" },
      { Id: "OSK-CHN-05", Name: "Sudha Anand" },
      { Id: "OSK-CHN-06", Name: "Praveen B G" },
      { Id: "OSK-CHN-07", Name: "Narayanan Nambidi K" },
      { Id: "OSK-CHN-08", Name: "Vasudevan K V" },
      { Id: "OSK-CHN-09", Name: "Rajesh R" },
    ],

    ഹൈദരാബാദ്: [
      { Id: "OSK-HYD-01", Name: "Mrs. K N Remadevi" },
      { Id: "OSK-HYD-02", Name: "P M Sreejith" },
    ],
  },
};

export const exOfficioMap = {
  തിരുവനന്തപുരം: {
    "EXO-TVM-01": {
      Name: "V S Raju",
      Designation: "President",
    },
    "EXO-TVM-02": {
      Name: "K M Sreedevi Kutty",
      Designation: "Secretary",
    },
  },
  കൊല്ലം: {
    "EXO-KLM-01": {
      Name: "C Vasudevan Nambiar",
      Designation: "President",
    },
    "EXO-KLM-02": {
      Name: "G Madhusoodanan Unni",
      Designation: "Secretary",
    },
  },
  പത്തനംതിട്ട: {
    "EXO-PTA-01": {
      Name: "Arun Das M P",
      Designation: "President",
    },
    "EXO-PTA-02": {
      Name: "Rema Sarma",
      Designation: "Secretary",
    },
  },
  കോട്ടയം: {
    "EXO-KTM-01": {
      Name: "K M Narayanan Unni",
      Designation: "President",
    },
    "EXO-KTM-02": {
      Name: "K S Krishnan Kumar",
      Designation: "Secretary",
    },
  },
  ഇടുക്കി: {
    "EXO-IDK-01": {
      Name: "Sindhu Vasudevan",
      Designation: "President",
    },
    "EXO-IDK-02": {
      Name: "M S Neelakantan Unni",
      Designation: "Secretary",
    },
  },
  ആലപ്പുഴ: {
    "EXO-ALP-01": {
      Name: "Pradeep K S",
      Designation: "President",
    },
    "EXO-ALP-02": {
      Name: "Aji R",
      Designation: "Secretary",
    },
  },
  എറണാകുളം: {
    "EXO-EKM-01": {
      Name: "R S Nambiar",
      Designation: "President",
    },
    "EXO-EKM-02": {
      Name: "Narayanan Vasudevan",
      Designation: "Secretary",
    },
  },
  തൃശ്ശൂർ: {
    "EXO-TSR-01": {
      Name: "P R Ramachandran",
      Designation: "President",
    },
    "EXO-TSR-02": {
      Name: "Dr. K R Harinarayanan",
      Designation: "Secretary",
    },
  },
  പാലക്കാട്: {
    "EXO-PKD-01": {
      Name: "K Balasubramanian Nambisan",
      Designation: "President",
    },
    "EXO-PKD-02": {
      Name: "T R D Nambisan",
      Designation: "Secretary",
    },
  },
  മലപ്പുറം: {
    "EXO-MLP-01": {
      Name: "K M Parameswaran Nambisan",
      Designation: "President",
    },
    "EXO-MLP-02": {
      Name: "Premlatha Unnikrishnan",
      Designation: "Secretary",
    },
  },
  കോഴിക്കോട്: {
    "EXO-CLT-01": {
      Name: "Padmanabha Nambisan",
      Designation: "President",
    },
    "EXO-CLT-02": {
      Name: "V D Dinesh Kumar",
      Designation: "Secretary",
    },
  },
  കണ്ണൂർ: {
    "EXO-KNR-01": {
      Name: "K M Raghunandan Nambisan",
      Designation: "President",
    },
    "EXO-KNR-02": {
      Name: "T M Suresh Babu",
      Designation: "Secretary",
    },
  },
  വയനാട്: {
    "EXO-WYD-01": {
      Name: "P Sivaraman Nambisan",
      Designation: "President",
    },
    "EXO-WYD-02": {
      Name: "T Vasudevan Nambisan",
      Designation: "Secretary",
    },
  },
  കാസർഗോഡ്: {
    "EXO-KGD-01": {
      Name: "N M Narayanan Nambisan",
      Designation: "President",
    },
    "EXO-KGD-02": {
      Name: "E Rajesh",
      Designation: "Secretary",
    },
  },
};
